/** Transport UI policy; endpoints remain the server-side BFF, never upstream URLs. */
export const transportClientConfig = {
  autocompleteDelayMs: 250,
  minimumQueryLength: 2,
  gpsMaxAgeMs: 30_000,
  lastKnownGpsMaxAgeMs: 90_000,
  gpsFutureToleranceMs: 5_000,
  gpsTimeoutMs: 12_000,
  autocompleteGpsTimeoutMs: 1_500,
  timeline: {
    predictionTickMs: 1_000,
    atStopMeters: 35,
    maxOffsetMeters: 120,
    ambiguityMeters: 25,
    minSegmentMeters: 10,
    maxSegmentMeters: 10000,
  },
  mapZoom: { stop: 17, picker: 13, journeyFitMax: 15, journeyOffset: 1 },
  defaultMapCenter: [14.42, 50.075] as [number, number],
  mapCenters: {
    NO: [10.752, 59.911],
    SK: [17.1077, 48.1486],
    AT: [16.3738, 48.2082],
    PL: [19.1451, 51.9194],
  } as Record<string, [number, number]>,
  endpoints: {
    presentation: "/api/transport/presentation/",
    attributions: "/api/transport/attributions/",
    coverage: "/api/transport/coverage/",
    tracking: "/api/transport/tracking/",
    observation: "/api/transport/observation/",
    cities: "/api/transport/cities/",
    places: "/api/transport/places/",
    search: "/api/transport/search/",
    trip: "/api/transport/trip/",
    stop: "/api/transport/stop/",
  },
};
